Gives Rodentia their own language, and a bit of lore! GLORY TO RATSTOZKA!
Grimbly-Station/Grimbly-Station pull request #107
Opened 2024-10-07 01:21 UTC by CometVoid

# Description

Gives rodentia their own language, Ratstozkan, and adds a Ratstozkan translator and translator implant.
Also adds a tidbit of my own lore to the language description:
>    After several leaks from the Tau-Ceti Government, it was recently determined that 'Ratstozka' wasn't ever a real empire, and therefore not the legitimate name of this language.
   Instead, 'Ratstozka' was a deameaning, made up name slapped on to the many rodentia nations to villainize them - ultimately being used to justify the liberation of the Rodentia Homeworld.
   Nowadays, many rodentia wish to reclaim their independance; While the false flag was originally a tool for oppression, it has been slowly turned into an icon of national pride.
   GLORY TO RATSTOZKA!

---

<h1>Media</h1>
<p>

![image](https://github.com/user-attachments/assets/dda73fc5-0f5e-4754-81f8-117fee647259)

</p>

---

# Changelog

:cl:
- add: Added Ratstozkan, the glorious language of the Rodentia!
- add: Rat kings can now speak Ratstozkan, and rat servants can understand Ratstozkan

2024-10-08 19:07 UTC, zelezniciar1 commented
This should fix the issues with RandomBarkSystem, correct?

2024-10-08 19:57 UTC, zelezniciar1 requested changes
Looks like the YAML Linter is failing on the translator implants, and I would also like to request #Grimbly comments wherever you have made changes to upstream YAML.

2024-10-12 20:05 UTC, CometVoid commented
alrighty, will fix this pr today.

2024-10-12 20:29 UTC, CometVoid commented
it should be fixed now.

2024-10-13 00:43 UTC, zelezniciar1 approved these changes
![bg,f8f8f8-flat,750x,075,f-pad,750x1000,f8f8f8 u2-2559936055](https://github.com/user-attachments/assets/0ec5559e-fdba-4ff3-822a-035fb92ad190)
PR Approved. Cause no trouble.

Glory to Ratstotzka!

2024-10-13 02:54 UTC, merged